ZoxNews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('details/<slug:slug>', views.PostDetailsView.as_view(), name='post_details'),
    path('update/<slug:slug>', views.PostUpdateView.as_view(), name='post_update'),
    path('category/<slug:slug>', views.CategorySortView.as_view(), name='category_sort'),
    # path('addlike/', views.add_to_liked, name='add_to_liked'),
    # path('comment/', views.comment, name='comment'),


]

api/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.

# Category Model
class Category(models.Model):
	name = models.CharField('Category name', max_length=100)
	slug = models.SlugField("*", max_length=100, unique=True)

	def __str__(self):
		return f"{self.name}"


# Tag Model 
class Tags(models.Model):
	name = models.CharField('Tag name', max_length=100)
	slug = models.SlugField("*", max_length=100, unique=True)

	def __str__(self):
		return f"{self.name}"
 

 #  Main Post model
class Post(models.Model):
	title = models.CharField("Title", max_length=300, blank=True)
	slug = models.SlugField("*", max_length=300, unique=True, blank=True)
	image_local = models.ImageField("Poster", upload_to='posters/', blank=True)
	image = models.URLField(max_length=200, blank=True)
	author = models.CharField("Author", max_length=100, blank=True)
	rich_body = RichTextField()
	published = models.DateTimeField(auto_now_add=True)
	views = models.PositiveIntegerField("Views", default=0)
	likes = models.PositiveIntegerField('Like', default=0 , blank=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts', blank=True, null=True)
	tag = models.ManyToManyField(Tags, blank=True)
	source = models.URLField(max_length=200)
	
	def __str__(self):
		return f"{self.title}"

	class Meta:
		ordering = ["-published",]
		verbose_name_plural = 'Posts'



# Model of Comment
class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField("Name", max_length=50)
	email = models.EmailField("Email", max_length=250)
	subject = models.CharField("Subject", max_length=100)
	message = models.TextField("Your Text",)

	def __str__(self):
		return f"{self.name}"

	class Meta:
		verbose_name='Comments'
		verbose_name_plural='Comments'


#  To Save Liked Posts Of The USER
class LikedPosts(models.Model):
	liked_posts = []
	
	def __str__(self):
		return f"Liked {self.id}"

api/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.http import JsonResponse
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Category, Post, LikedPosts
from django.views.generic import DetailView, ListView, UpdateView
import json


# Main Home page
class HomePageView(ListView):
    model = Post
    template_name = 'index.html'

#  For Post details
class PostDetailsView(DetailView):
    model = Post
    template_name  = 'post-details.html'

# Sorting By category
class CategorySortView(DetailView):
    model = Category
    template_name  = 'category-sort.html'

# For Updating Posts
class PostUpdateView(UpdateView):
    model = Post
    template_name = "post_update.html"
    fields = '__all__'
    success_url = '/'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>World Time</title>
    <!-- plugin css for this page -->
    <link
      rel="stylesheet"
      href="./assets/vendors/mdi/css/materialdesignicons.min.css"
    />
    <link rel="stylesheet" href="/static/assets/vendors/aos/dist/aos.css/aos.css" />

    <!-- End plugin css for this page -->
    <link rel="shortcut icon" href="/static/assets/images/favicon.png" />

    <!-- inject:css -->
    <link rel="stylesheet" href="/static/assets/css/style.css">
    <!-- endinject -->
  </head>

  <body>
    <div class="container-scroller">
      <div class="main-panel">
        <!-- partial:partials/_navbar.html -->
        <header id="header">
          <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
              <div class="navbar-top">
                <div class="d-flex justify-content-between align-items-center">
                  <ul class="navbar-top-left-menu">
                    <li class="nav-item">
                      <a href="/static/pages/index-inner.html" class="nav-link">Advertise</a>
                    </li>
                    <li class="nav-item">
                      <a href="/static/pages/aboutus.html" class="nav-link">About</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Events</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Write for Us</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">In the Press</a>
                    </li>
                  </ul>
                  <ul class="navbar-top-right-menu">
                    <li class="nav-item">
                      <a href="#" class="nav-link"><i class="mdi mdi-magnify"></i></a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Login</a>
                    </li>
                    <li class="nav-item">
                      <a href="#" class="nav-link">Sign in</a>
                    </li>
                    <li class="nav-item">

                        
                    </li>
                  </ul>
                </div>
              </div>
              <div class="navbar-bottom">
                <div class="d-flex justify-content-between align-items-center">
                  <div>
                    <a class="navbar-brand" href="#"
                      ><img src="/static/assets/images/logo.svg" alt=""
                    /></a>



<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
  +
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="">        
          {{post_form.as_p}}
        </form>

        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>







                  </div>
                  <div>
                    <button
                      class="navbar-toggler"
                      type="button"
                      data-target="#navbarSupportedContent"
                      aria-controls="navbarSupportedContent"
                      aria-expanded="false"
                      aria-label="Toggle navigation"
                    >
                      <span class="navbar-toggler-icon"></span>
                    </button>
                    <div
                      class="navbar-collapse justify-content-center collapse"
                      id="navbarSupportedContent"
                    >
                    <button class=" navbar-close navbar-nav d-lg-flex justify-content-between align-items-center " > Close </button>
                      <ul
                        class="navbar-nav d-lg-flex justify-content-between align-items-center"
                      >
                        <li>
                          <!-- <button class="navbar-close " style="" >
                            <i class="mdi mdi-close"></i>
                          </button> -->
                        </li>                        
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'main:home'  %}"> HOME  </a>
                        </li>
                        {% for category in categories %}
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'main:category_sort' category.slug %}"> {{category.name}}  </a>
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                  <ul class="social-media">
                    <li>
                      <a href="#">
                        <i class="mdi mdi-facebook"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-youtube"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="mdi mdi-twitter"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          </div>
        </header>



{% block content %}
    
{% endblock content %}

        <!-- partial:partials/_footer.html -->
        <footer>
            <div class="footer-bottom">
              <div class="container">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="d-sm-flex justify-content-between align-items-center">
                      <div class="fs-14 font-weight-600">
                        © 2020 @ <a href="https://www.bootstrapdash.com/" target="_blank" class="text-white"> BootstrapDash</a>. All rights reserved.
                      </div>
                      <div class="fs-14 font-weight-600">
                        Handcrafted by <a href="https://www.bootstrapdash.com/" target="_blank" class="text-white">BootstrapDash</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </footer>
  
          <!-- partial -->
        </div>
      </div>
      <!-- inject:js -->
      <script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>
      <!-- endinject -->
      <!-- plugin js for this page -->
      <script src="/static/assets/vendors/aos/dist/aos.js/aos.js"></script>
      <!-- End plugin js for this page -->
      <!-- Custom js for this page-->
      <script src="/static/assets/js/demo.js"></script>
      <script src="/BlogAnd/static/assets/js/demo.js" ></script>
      <script src="/static/assets/js/jquery.easeScroll.js"></script>
      <!-- End custom js for this page-->


      <script>
        window.onload = ()=> {
          let d = new Date()
          console.log(d.toString().slice(0,15))
          document.getElementById("time").innerHTML = d.toString().slice(0,21);
        }
    </script>
    </body>
  </html>
  

templates/category-sort.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

<h3> {{object.name}} </h3> 


{% for post in object.posts.all %}
        <h3> {{post.title}} </h3>
        <h4> {{post.body}} </h4>
     <br>
     
     {% if post.image %}
        <img src="{{post.image.url}}  " alt="Image Not Found" style="width: 200px;height: 150px;">
     {% else %}
     <img
     src="/static/assets/images/dashboard/home_5.jpg"
     alt="thumb"
     class="img-fluid"
   />
     {% endif %}
             
{% endfor %}
{% endblock content %}
    

templates/post-details.html
{% extends 'base.html' %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {% if object.image %}
                <img src="{{object.image}}" alt="Post-Image" class="img-fluid" >
                {% else %}
                <img
                src="{{image_local.url}}"
                alt="thumb"
                class="img-fluid"
              />
                {% endif %}
            </div>
            <div class="col-md-6">
                <div class="card-body">
                    <h1>{{object.title}}</h1>
                    <span id="num_of_likes">{{object.likes}}</span> <br>
                    <span id="date">{{object.published | date:" M H:i"}}</span> <br>
                    
                    {% if request.user.is_staff %}
                    <a href="{{object.source}}" id="source"> Original Post </a> <br>
                    {% endif %}
                        
                    
                    {% if post.id in liked_posts.liked_posts %}
                        {% else %}    
                    <button onclick="Like({{object.id}}) " class="btn btn-group btn-outline-danger"> Like</button>
                    {% endif %}
                        
                    <form action="/comment/">
                        <input type="text" value="{{post.slug}}" name="post_slug" hidden>
                    {% csrf_token %}
                        <input type="text" name="name">
                        <button type="submit" >s</button>
                </form>
                </div>
            </div>
        </div>
    </div>

        
    {{object.rich_body | safe}}
    



<style>
    p{
        font-weight: 500;
    }
</style>





<script>

function Like(post_id){
    let d = {
        post_id:post_id,
    }
    let data = JSON.stringify(d)
	  if (window.XMLHttpRequest) {
      var xhttp=new XMLHttpRequest();
    } else {  // code for IE6, IE5
        var xhttp=new ActiveXObject("Microsoft.XMLHTTP");
    }
    xhttp.onreadystatechange = function() {
    if (xhttp.readyState === 4 && xhttp.status === 200) {
      var data = JSON.parse(this.responseText);
        console.log(data['product_like'])
        document.getElementById("num_of_likes").innerHTML = data['product_like']
    }else{
      console.log('not yet')

      }
    }
    var url = "/addlike/"
    xhttp.open("GET", url+`?data=${data}`, true);
    xhttp.send();
}
</script>





    {% endblock content %}
    

templates/post_update.html
{% extends 'base.html' %}


{% block title %}
AndBugun|uUpdate    
{% endblock title %}
    

{% block content %}


{% if object.image %}
<img src="{{object.image.url}}" alt="">
    
{% endif %}
    
<script src="https://cdn.ckeditor.com/ckeditor5/31.0.0/classic/ckeditor.js"></script>
<form action="" method="POST">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button type="submit"> Submit </button>
</form>

<script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>


{% endblock content %}
    